name: Deploy New Markdown
on: [workflow_dispatch,issues]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Install curl
        run: apk add --no-cache curl
      - uses: actions/checkout@v2
      - name: Create output directory
        run: mkdir -p output
      - name: creates output
        run: sh ./convert.sh
      - name: checks output
        run: ls output
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output
          destination-github-username: 'learlab'
          destination-repository-name: 'itell-strapi-demo'
          target-directory: apps/example-poe/content/section
          user-email: annachen031014@gmail.com
          commit-message: Added new content
          target-branch: main
      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: output
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
