name: Deploy New Markdown
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'text name'
        required: true
        type: string
      token:
        description: 'github token'
        required: true
        type: string
      owner:
        description: 'designation repo owner'
        required: true
        type: string
      repository:
        description: 'designation repo name'
        required: true
        type: string
      dir:
        description: 'designated repo path'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Install curl
        run: apk add --no-cache curl jq nodejs npm
      - name: Create output directory
        run: npm install node-fetch
      - uses: actions/checkout@v2
      - name: Create output directory
        run: mkdir -p output
      - name: creates output
        run: node ./testing.js
          echo "Contents of output directory after script:"
          ls -R output
      - name: List contents of the output directory
        run: ls -R output
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ inputs.token }}
        with:
          source-directory: output
          destination-github-username: ${{ inputs.owner }}
          destination-repository-name: ${{ inputs.repository }}
          target-directory: ${{ inputs.dir }}
          user-email: annachen031014@gmail.com
          commit-message: Added new content
          target-branch: main
      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: output
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
